# Records every line in lines.json with the French voice "Pierre" (Piper, upmc, speaker 1) and writes voice.js.
# Needs: pip install sherpa-onnx soundfile numpy, ffmpeg, and the model folder vits-piper-fr_FR-upmc-medium from
# https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-fr_FR-upmc-medium.tar.bz2
# Run from outils/voix/ after getlines.js.
import json, os, subprocess, base64, hashlib, numpy as np, soundfile as sf, sherpa_onnx
D = "vits-piper-fr_FR-upmc-medium"
tts = sherpa_onnx.OfflineTts(sherpa_onnx.OfflineTtsConfig(model=sherpa_onnx.OfflineTtsModelConfig(
    vits=sherpa_onnx.OfflineTtsVitsModelConfig(model=f"{D}/fr_FR-upmc-medium.onnx", tokens=f"{D}/tokens.txt", data_dir=f"{D}/espeak-ng-data"),
    num_threads=4)))
lines = json.load(open("lines.json")); os.makedirs("clips-pierre", exist_ok=True)
out = {}
for i, t in enumerate(lines):
    name = "clips-pierre/" + hashlib.md5(t.encode()).hexdigest()[:12]
    if not os.path.exists(name + ".mp3"):
        a = tts.generate(t[0].upper() + t[1:], sid=1, speed=0.95)
        s, sr = np.asarray(a.samples, dtype=np.float32), a.sample_rate
        nz = np.nonzero(np.abs(s) > 0.01)[0]
        if len(nz): s = s[max(0, nz[0] - int(sr * 0.01)): nz[-1] + int(sr * 0.04)]
        sf.write(name + ".wav", s, sr)
        subprocess.run(["ffmpeg", "-loglevel", "error", "-y", "-i", name + ".wav", "-ac", "1", "-b:a", "32k", name + ".mp3"], check=True)
        os.remove(name + ".wav")
    out[t] = base64.b64encode(open(name + ".mp3", "rb").read()).decode()
    if i % 100 == 0: print(i, t, flush=True)
js = "// Recorded French voice for Le Train des Animaux (Piper, voice upmc \"Pierre\"). Generated by outils/voix/gen.py, do not edit by hand.\nwindow.VOICE_CLIPS = " + json.dumps(out, ensure_ascii=False, separators=(",\n", ":")) + ";\n"
open(os.environ.get("OUT", "../../voice.js"), "w").write(js); print("done", len(out), len(js))
